export const CLEAR_ALERT = "CLEAR_ALERT"

export const UPLOAD_IMAGE_BEGIN = "UPLOAD_FILE_BEGIN"
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR"

export const GET_IMAGES_BEGIN = "GET_IMAGES_BEGIN"
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS"
export const GET_IMAGES_ERROR = "GET_IMAGES_ERROR"

export const GET_IMAGE_BEGIN = "GET_IMAGE_DATA"
export const GET_IMAGE_SUCCESS = "GET_IMAGE_DATA_S"
export const GET_IMAGE_ERROR = "GET_IMAGE_ERROR"